name: bharatcloud
description: BharatCloud B2C mobile app v1.1
publish_to: "none"
version: 1.1.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.3
  flutter_secure_storage: ^9.2.2
  local_auth: ^2.3.0
  image_picker: ^1.1.2
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
